# Use an official Python runtime as a parent image
FROM python:3.12-slim-bullseye

LABEL maintainer="Satish Kumar Sinha"
LABEL version="1.0"
ENV TZ="Asia/Kolkata"

# Set environment variables
#ENV PYTHONDONTWRITEBYTECODE 1
#ENV PYTHONUNBUFFERED 1

# Set the working directory inside the container
WORKDIR /opt/

# Copy the requirements file and install Python dependencies
COPY requirements.txt .

# Install system dependencies
RUN apt-get update && \
    apt-get install -y gcc libpq-dev vim&& \
   pip install --upgrade pip && \
   apt-get remove -y gcc libpq-dev && \
    apt-get autoremove -y && \
    apt-get clean && \
   rm -rf /var/lib/apt/lists/*


# Install Python dependencies and clean up
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir python-multipart fastapi-cli


RUN mkdir logs
RUN pip install strawberry-graphql

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1  # Prevent Python from writing .pyc files to disk
ENV PYTHONUNBUFFERED 1  # Force Python to output to stdout and stderr without buffering

# Copy the rest of the application code and config file into the container
COPY src_code/. /opt/
COPY local_config/. /opt/

# Expose the port FastAPI will run on
EXPOSE 8020

# Command to run the FastAPI app using Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8020", "--timeout-keep-alive", "10000", "--header", "server:openforge", "--reload"]
